[package]
name = "onetdns-dnscrypt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
onetdns-core.workspace = true
x25519-dalek.workspace = true
ed25519-dalek.workspace = true
chacha20 = "0.9"
poly1305 = "0.8"
zeroize.workspace = true

[lints]
workspace = true
