server:
    verbosity: 0
    interface: 127.0.0.1@15354
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: no
    do-daemonize: no
    use-syslog: no
    chroot: ""
    username: ""
    pidfile: ""
    num-threads: 1
    so-reuseport: no
    access-control: 127.0.0.0/8 allow
    do-not-query-localhost: no
    module-config: "iterator"
    msg-cache-size: 64m
    rrset-cache-size: 64m
    cache-min-ttl: 0
    cache-max-ttl: 86400
    prefetch: no
    qname-minimisation: no
    hide-identity: yes
    hide-version: yes
    local-zone: "test." nodefault

forward-zone:
    name: "."
    forward-addr: 127.0.0.1@15400
