[package]
name = "onetdns-control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["dashboard"]
dashboard = []

[dependencies]
onetdns-core.workspace = true
onetdns-proto.workspace = true
sha2.workspace = true
sha1.workspace = true
hmac.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[lints]
workspace = true
