[package]
name = "onetdns-forward"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
onetdns-proto.workspace = true
onetdns-core.workspace = true
onetdns-tls.workspace = true
onetdns-http2.workspace = true
onetdns-quic.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
onetdns-runtime.workspace = true
rcgen = "0.13"

[lints]
workspace = true
